#!/usr/bin/env bash
# Idempotent installer for the `kid` dsh profile. Builds the dsh-kid-tutor
# bundle, then materializes a dedicated $DSH_HOME under $HOME/.dsh-kid with
# its own profile, agent preset, workspace, credentials, and settings.
#
# Env (all read by the dsh-kid-tutor process at launch, never written to a
# file this repo tracks -- pass them on the same command line printed at the
# end of this script, or export them in whatever launches dsh as a service):
#   KID_NAME                    - the kid's name. Default: "friend".
#   KID_ALERT_WEBHOOK_URL       - parent-alert target (e.g. an ntfy topic
#                                 URL). Empty/unset disables alerting.
#   KID_ALERT_WEBHOOK_HEADERS   - optional JSON object string of extra
#                                 headers (e.g. '{"Title":"Kid Tutor Alert"}').
#   DSH_KID_HOME                - override the kid DSH_HOME. Default: $HOME/.dsh-kid.
set -euo pipefail

REPO_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
DSH_KID_HOME="${DSH_KID_HOME:-$HOME/.dsh-kid}"
KID_NAME="${KID_NAME:-friend}"

for bin in pnpm dsh; do
  if ! command -v "$bin" >/dev/null 2>&1; then
    echo "install.sh: '$bin' not found on PATH; install it first." >&2
    exit 1
  fi
done

echo "==> Building dsh-kid-tutor ($REPO_DIR)"
(cd "$REPO_DIR" && pnpm install && pnpm --filter dsh-kid-tutor run build)

echo "==> Creating $DSH_KID_HOME"
mkdir -p "$DSH_KID_HOME" "$DSH_KID_HOME/profiles" "$DSH_KID_HOME/.agent-presets" "$DSH_KID_HOME/workspace"

echo "==> Profile: $DSH_KID_HOME/profiles/kid (fresh copy from repo template)"
# A copy, not a symlink: profiles/kid/package.json needs an absolute link:
# dependency and this profile is meant to be a normal writable dsh profile
# directory (dsh itself may write generated files under it). Re-running this
# script always resets it to the repo's current template — any local edits
# made directly under $DSH_KID_HOME/profiles/kid do not survive a re-install.
rm -rf "$DSH_KID_HOME/profiles/kid"
cp -R "$REPO_DIR/profiles/kid" "$DSH_KID_HOME/profiles/kid"

echo "==> Agent preset: $DSH_KID_HOME/.agent-presets/kid"
# A REAL directory (not a symlinked one). Verified against the installed
# @deepseek-ai/dsh-agent-presets (lib/index.js, scanRoot()): discovery calls
# `child.isDirectory()` on each entry of `<dshHome>/.agent-presets` straight
# from `fs.readdir(..., { withFileTypes: true })`, and a Dirent's
# `isDirectory()` does NOT follow symlinks -- it reports the entry's own type
# (`isSymbolicLink()` true, `isDirectory()` false), so a symlinked preset
# DIRECTORY is silently invisible to discovery: not even reported broken,
# `session.create` just returns `agent-preset-not-found` naming only the
# shipped presets (confirmed on this machine).
#
# `preset.yml` (display metadata only, no paths) is symlinked -- editing it
# in the repo takes effect immediately. `agent.cordis.yml` is instead
# generated by substituting the __DSH_KID_TUTOR_DIST__ placeholder (see the
# comment at the top of presets/kid/agent.cordis.yml for the full reasoning:
# a relative plugin path from a symlinked FILE inside a real directory
# resolves relative to that real directory, not this repo, so an absolute,
# install-time-known path is what actually works). This means an edit to
# presets/kid/agent.cordis.yml needs a re-run of this script to take effect
# -- same trade-off profiles/kid already accepts.
mkdir -p "$DSH_KID_HOME/.agent-presets/kid"
ln -sfn "$REPO_DIR/presets/kid/preset.yml" "$DSH_KID_HOME/.agent-presets/kid/preset.yml"
sed "s|__DSH_KID_TUTOR_DIST__|$REPO_DIR/packages/dsh-kid-tutor/dist|g" \
  "$REPO_DIR/presets/kid/agent.cordis.yml" > "$DSH_KID_HOME/.agent-presets/kid/agent.cordis.yml"

echo "==> Credentials: symlinking ~/.dsh/.credentials.yaml"
if [[ -f "$HOME/.dsh/.credentials.yaml" ]]; then
  ln -sfn "$HOME/.dsh/.credentials.yaml" "$DSH_KID_HOME/.credentials.yaml"
else
  echo "    warning: $HOME/.dsh/.credentials.yaml not found -- the kid profile will have no model credentials until one exists there." >&2
fi

echo "==> Settings: $DSH_KID_HOME/settings.yaml"
if [[ -f "$HOME/.dsh/settings.yaml" ]]; then
  # Copied, then its agent-default-model section is forced back to the kid's
  # own route. Inspected at authoring time (key names only, never printed
  # values): this file held only agent-default-model / llm-* provider routing
  # (baseURL, apiKeyEnv references, model lists) -- no key material, which
  # lives solely in .credentials.yaml (symlinked above, never copied). If
  # ~/.dsh/settings.yaml's shape ever changes to include anything else,
  # re-check before trusting this copy.
  #
  # Confirmed on this machine: settings.yaml's agent-default-model OVERRIDES
  # the profile's cordis.patch.yml row of the same id at runtime (a session
  # actually ran under deepseek-v4-pro despite the patch saying flash, until
  # this override was added) -- settings.yaml is the live store the web UI's
  # model picker writes to, so it wins over the Loader's static default.
  # Copying a parent's personal settings.yaml verbatim would silently hand
  # the kid whatever stronger/costlier model and reasoning effort the parent
  # last picked for themselves.
  cp "$HOME/.dsh/settings.yaml" "$DSH_KID_HOME/settings.yaml"
  python3 - "$DSH_KID_HOME/settings.yaml" <<'PY'
import sys
import yaml

path = sys.argv[1]
with open(path) as f:
    data = yaml.safe_load(f) or {}
data["agent-default-model"] = {"provider": "deepseek-official", "model": "deepseek-v4-flash"}
with open(path, "w") as f:
    yaml.safe_dump(data, f, default_flow_style=False, sort_keys=False)
PY
else
  cat > "$DSH_KID_HOME/settings.yaml" <<'YAML'
agent-default-model:
  provider: deepseek-official
  model: deepseek-v4-flash
YAML
fi

echo "==> pnpm install in $DSH_KID_HOME/profiles/kid"
(cd "$DSH_KID_HOME/profiles/kid" && pnpm install)

# ADMIN: the kid-admin profile is a separate package this script does not
# own (docs/CONTRACT.md's admin bundle). If its own installer exists, run it
# too, so one `install.sh` sets up both profiles end to end.
if [[ -x "$REPO_DIR/scripts/install-admin.sh" ]]; then
  echo "==> Running scripts/install-admin.sh"
  "$REPO_DIR/scripts/install-admin.sh"
fi

cat <<EOF

Install complete. Start the kid profile with:

  KID_NAME="$KID_NAME" DSH_HOME="$DSH_KID_HOME" dsh --profile kid --port 3081 --no-open

Parent alerts are OFF by default. To turn them on, add before "dsh":
  KID_ALERT_WEBHOOK_URL="<your ntfy topic or webhook URL>"

EOF
